### ISSUE TITLE
addType is removing connection overlays that already exist.

### ISSUE THREAD

**Issue by Deklin** [sporritt/jsPlumb#288]
e.g.

First i'm registering my styles
In this case NORMAL_CLASS is "normal" and SELECTED_CLASS is "selected"

 var connectionTypes = {};
    connectionTypes[TopologyDesigner.NORMAL_CLASS] = {
        paintStyle: {
            strokeStyle: "gray",
            lineWidth: 3,
            cssClass: TopologyDesigner.NORMAL_CLASS
        },
        hoverPaintStyle: {
            strokeStyle: "#64c8c8",
            lineWidth: 3
        }
    };
    connectionTypes[TopologyDesigner.SELECTED_CLASS] = {
        paintStyle: {
            strokeStyle: "blue",
            lineWidth: 3,
            cssClass: TopologyDesigner.SELECTED_CLASS

        },
        hoverPaintStyle: {
            strokeStyle: "#64c8c8",
            lineWidth: 3
        }
    };

    this._designerInstance.registerConnectionTypes(connectionTypes);

When I perform a connection, i'm doing this;

    this._designerInstance.connect({
        source: $source,
        target: $target,
        detachable: true,
        overlays: [
            ["Label",
                {
                    label: "hello",
                    location: 50,
                    id: "myLabel1",
                    cssClass: "connectionLabel"
                }
            ]
        ],
        data: relationship,
        type: TopologyDesigner.NORMAL_CLASS
    });

If I don't specify type on the connection, my overlay appears, if I then use an addType of NORMAL or Selected, i lose my label overlay.

According to the doc this should not occur;
overlays - when you have multiple types applied to a Connection, you get the union of all the Overlays defined across the various Types. Note when you create a Connection using jsPlumb.connect and you provide a 'type', that is equivalent to calling 'addType': you will get the Overlays defined by the Type(s) you set as well as any others you have provided to the constructor

**Comment by sporritt** [comment]
@Deklin If you need to reopen an issue please feel free to do so rather than creating a new issue. it keeps everything more maintainable.

Here's your reopen comment:

---

I tested the patch on both 1.7.3. alpha as well as pulled the change for 288 and unfortunately the issue still exists.

What is happening is when you use addType on a connection, the overlay is reset back to default. 

If its a custom overlay, its reset, if its a label overlay the label value is blown away.

A simple way to test this is 
Following the unit test here;
https://github.com/sporritt/jsPlumb/commit/bc1a450b430dba6b7bab9bfb556239cccb209100

        ok(e.getOverlay("myLabel1") != null, "label overlay was retrieved");
+
+        e.addType("selected");
+        ok(e.getOverlay("myLabel1") != null, "label overlay was not blown away");
+        e.removeType("selected");
+        ok(e.getOverlay("myLabel1") != null, "label overlay was not blown away");

This is not in fact destroying the label, instead do this

var labelOverlay;
labelOverlay = e.getOverlay("myLabel1");
labelOverlay.setLabel("foo");
ok(labelOverlay.getLabel() === "foo");
e.addType("selected");
labelOverlay = e.getOverlay("myLabel1");
ok(labelOverlay.getLabel() === "foo"); // This will fail as label was reset

If you perform the same test with a custom overlay, the entire overlay is also reset back to its initial 'create' state.

**Comment by sporritt** [comment]
so...this isn't a reopen in fact is it.  i mean it's not the issue that was fixed, it's something else.

**Comment by sporritt** [comment]
i will reopen #311  and leave this closed.
