### ISSUE TITLE
draggable not working in chrome

### ISSUE THREAD

**Issue by yvesgoeleven** [sporritt/jsPlumb#295]
Looks like the vanilla version of draggable is not working in chrome (version 39.0.2171.71), it works perfectly in other browsers tough, the jquery version works as well. 

I tried the drag drop demo on the website, http://www.jsplumb.org/demo/draggableConnectors/dom.html as well as any other demo I could find online, non of these seem to work in chrome.

**Comment by sporritt** [comment]
@yvesgoeleven @smiling-Jack looks like this will make it into 1.7.5...the touch stuff, anyway. i don't know about win10. might have to split that out into a separate issue if it turns out to be something. 

anyway - latest 1.7.5 dev is pushed. perhaps you could give it a try on a touchscreen window device.

**Comment by sporritt** [comment]
closing.  i have tested the `draggableConnectors` demo on a windows touch laptop in chrome and IE and it works with both mouse and touch events. FF on that machine reports that touch events are not available; there seems to be some confusion about FF's touch event support at the moment.
