### ISSUE TITLE
add support for groups

### ISSUE THREAD

**Issue by Deklin** [sporritt/jsPlumb#312]
This may just be a limitation of jsPlumb so if so just consider this an ER.

Here is our canvas

<div id="canvas">
<div id="node1"></div>
<div id="node2"></div>
<div id="node3"></div>
</div>

Node 1 connected to node 2
All nodes draggable.

This obviously works great.

However if we want to do something like this (we wanted to implement grouped nodes.

<div id="canvas">
<div id="group1">
   <div id="node1"></div>
   <div id="node2"></div>
</div>
<div id="node3"></div>
</div>

When nodes are moved around, jsplumb loses the proper coordinates of where the connector should go.

Here is a fiddle;
http://jsfiddle.net/sberube/3sjdqxbd/

Poorly done (sorry)

Drag the gray box around.
Notice the nodes move (group is draggable)
Notice the connectors go haywire.
I have repaintEverything being run on group move, but as you can see the endpoints are off by exactly how much the group has moved from 0.0.

Is it possible in the current jsPlumb to support this concept?

**Comment by sporritt** [comment]
are you just trying to drag multiple nodes at once?

**Comment by sporritt** [comment]
(if so)

http://blog.jsplumbtoolkit.com/posts/multiple-element-drag.html

**Comment by Deklin** [comment]
Not quite; We are going for this approach;
http://jsfiddle.net/sberube/pz3yks5g/

Drag some of the circles around, in this mockup the containers auto-resize and position based on the elements.

So what we want to do is two things

1. Have this ability for groups to resize around nodes (we got that covered)
2. Let groups be movable (we got that covered)

But what we hit (besides this issue) was it was hard to tell when a group was over other nodes that those nodes were not part of the group

To solve this, we will z-index the groups higher so the other nodes appear behind the group.

But then we hit the issue of when a node is in a sub element, the connector positioning gets off. I'm going to look at the jsplumb code today, My guess it is assuming its in the 'container' vs calculating offets up to the container.

Here is a picture of our work so far
https://www.dropbox.com/s/ryqeo2x44sosbdx/jsplumb.png?dl=0

I've hacked the node that is behind the group with a z-index = -1 to show our desired result. It is very close to working, My guess is if I solve the container calculation offset issue it will work properly.

**Comment by sporritt** [comment]
Yes it's the container offset calculation that causes what you see.

**Comment by Deklin** [comment]
Ok you know the code better than I, i'm going to look today but it seems beneficial to add some logic to the node positioning to determine its location based off the container (up the dom to container from node). Any hits where you'd recommend I start?

I'm going to attempt this to see if we can resolve our issue.

**Comment by Deklin** [comment]
I've got a potential workaround. Still implementing drag group however have a look.

http://jsfiddle.net/Lnzxy8dL/

**Comment by Deklin** [comment]
Workaround updated - not overly pleased with it, but it has the desired user experience; Same fiddle as above, move nodes around, move group (background color) around.

**Comment by sporritt** [comment]
@Deklin i just circled back to look at this and found that the original fiddle is gone:

http://jsfiddle.net/sberube/3sjdqxbd/

the last one you put up has a whole load of code...it's not really very clear to me what i'd be trying to fix.  a real simple test case (such as i think the missing one was?) would be good.

**Comment by Deklin** [comment]
I'll create a simple test case for you. The fiddle I had was the goal we wanted:
http://jsfiddle.net/sberube/Lnzxy8dL/

That is the goal;

I had to hack it to get it to do that, its a viable workaround for us but i'll create a new fiddle shortly which shows the issue.

Thanks again.

**Comment by sporritt** [comment]
thanks, yeah..i know that's the goal.  but in that fiddle i cant see the problem for the er, trees. or the forest, or...whatever.

**Comment by Deklin** [comment]
http://jsfiddle.net/sberube/sv72xxwL/

Ok I removed all the group auto-sizing;

Basically you have 2 groups in the dom.

Drag the color on the top left to move the nodes around;
Observe those drag fine (due to repaintEverything()

Move nodes around, observe the node connection gets offset by the amount the group has been moved from 0,0 position.

**Comment by sporritt** [comment]
@Deklin I've updated this to 1.7.4

http://jsfiddle.net/sv72xxwL/11/

you've probably figured a workaround by now, but i know why it exhibits the behaviour you're seeing: the code that calculates the offset of the element being dragged expects that the offsetParent be the same as the current container. In this case the offsetParent is a `.group` node, which itself has the container as its offsetParent. I think this could be considered a bug, really.

**Comment by sporritt** [comment]
...in fact rather than treat this as a bug I might instead use it as a place to start out thinking about supporting groups in jsplumb. in your fiddle you can drag an entire group around and all the nodes get updated, but only because you call `jsPlumb.repaintEverything`; it would be nicer if you could nominate elements as 'groups' and have this taken care of for you (also I'm not sure if you've noticed but you get a slight lag calling `repaintEverything` like that...a properly integrated 'group' solution would eliminate that lag.  should, that is!).

the other characteristic of your fiddle (not the last one i know) is that dragging the nodes causes the container to be resized. It strikes me that this feature would be best done via a switch, since not everyone will want that. Some people will want no resizing, some will want containment to the parent, etc.

One other thing that is not shown in your code but which I assume is something you either are doing or would like to do is the ability to collapse a group, with the re-routing of connections that that would entail.

Support for groups has been on the horizon for a while with jsPlumb, or at least the fact that it would one day become desirable has been.  So perhaps this is a good time for me to think about it.

**Comment by Deklin** [comment]
At this time we didn't have a need for collapsing groups but I agree great
feature. The group 'hack 'i did has been working out very well thus far!

We are at 1.7.3 right now, we had an issue with 1.7.4 I have't had time to
troubleshoot yet.

**Comment by Deklin** [comment]
The lag with repaintEverything we notice the most with IE and Firefox,
Chrome does a pretty good job for some reason. Overall the technique has
been working very well, we've added some more enhancements to it and the
core JSPlumb code has been very solid.

**Comment by sporritt** [comment]
renamed from "Nodes in sub elements do not have connectors properly positioned"

**Comment by sporritt** [comment]
What sort of api methods would be useful for you?

 Create a group and give it an id?

 Create a group and specify an id and a selector?

  Add a node/some nodes to a group? 

Merge two groups? 

Delete an entire group?

**Comment by Deklin** [comment]
1. Yes a Group should have an ID Associated with it
2. Some useful apis addNodeToGroup, getNodesInGroup, removeNodeFromGroup,
removeAllNodesFromGroup, getGroups, getGroup, removeGroup, combineGroups,
expandGroup, collapseGroup
3. For our requirements a node can only belong to a single group or no
groups.
4. Some drop mechanic so we can drop a node into a group
5. For us, we always modified the DOM to put the group element last to make
the selected/dragging group appear on top of everything else.
6. Ability to specify style types for groups like we can for nodes.
7. expand/collapse groups (not sure what happens to connections to nodes
INT hat group, if they all show a connection to the collapsed group...
8. Can connections happen to a group itself?

I'll give it some more though, but here are some starting ideas.

**Comment by herringtown** [comment]
^^ I would also work on the proper mechanism to infer a user's drag intent for nodes both inside and outside groups.  For instance, user could be dragging a "grouped nod"e towards the border/container of the group with the intent to drag it *out* of the group, *OR*, perhaps with the intent for the group's border/container to expand. 

I also love the idea of being able to have connections in/out of groups themselves -- it is a fantastic way to indicate a logical subprocess as a sort of nested diagram...

Looking forward to watch the progress here -- this is an awesome project...!

**Comment by ivosantiago** [comment]
:+1: 

I'm really new to this toolkit and I was trying to create all this features myself before I saw this thread. Is there any update about groups?

Thanks

**Comment by sporritt** [comment]
Not as yet. But this is something we need to start thinking about soon, for both open source and Toolkit versions.

**Comment by ivosantiago** [comment]
@sporritt I'm trying to make sense about how the project is organized. I'm half way done with groups but not sure how can I plug my code here. Is there any contributing guideline?

Thanks

**Comment by sporritt** [comment]
There isn't a contributor's guideline, no.  Noone has ever landed a feature such as what you might be talking about.

But maybe can you tell me what it is you are planning? This discussion contains various suggestions and comments and when I got to this work my first task was going to be to sort through them and come up with a spec.

**Comment by Deklin** [comment]
Simon; I can share the group code we have, but it is only a portion of the
user stories I originally provided a while back. It more deals with nodes
in a group and moving them around/html positioning. In our code groups
cannot have actual connections. So while some of the code may be
inspirational, i doubt it will have use in the core code base.

**Comment by sporritt** [comment]
@ivosantiago @Deklin I am starting to look at this now.  Initial support needs to be added to Katavorio first; there are a couple of issues tracking this:

https://github.com/jsplumb/katavorio/issues/23

https://github.com/jsplumb/katavorio/issues/22

once these are done i can look at the jsplumb layer.

**Comment by Deklin** [comment]
Outstanding!

**Comment by herringtown** [comment]
Ahoy, just popping in here to check on the status of the group spec.  @sporritt any updates on that?

Also, @ivosantiago, @Deklin , any updated fiddles that demo the work you have put in to your forks for group functionality (I think the current ones above might be broken/outdated) ?

**Comment by sporritt** [comment]
it's inching forwards.  This is a kind-of spec in progress for the work involved in the Community edition. Comments welcome.


#### Assumptions

- Nodes in a Group are children, in the DOM, of some Group container.
- Nodes in a Group are draggable inside the Group (or at least, may be)
- Connections may be made from elements in the Group to elements outside of the Group
- Connections may be made between elements in a Group
- Group containers are draggable (or at least, may be).
- On Group collapse, a strategy should be enacted that re-routes any connections to elements inside the group so that they now attach to the Group container. User should be able to specify the anchor/endpoint combination to use for the connection points on a collapsed Group container.
- On Group expand, connections should re-route to their appropriate elements.
- Connections to an expanded Group container are not permitted. A Group is not a connectable element; it is just a proxy.

#### Requirements

##### Community Edition

- Ensure jsPlumb can handle connections between elements when one element’s parent is not the Container of the jsPlumb instance. We believe this is possible now; there were a few issues related to this in the past.

- Support a mechanism for a user to indicate to the jsPlumb Community edition that some element belongs to some named Group.

- Support a mechanism to remove an element from a Group

- Support a mechanism to move an element from one Group to some other Group

- Support a mechanism to mark some element as a Group container

- add a groupCollapse method which collapses a Group (this will likely simply mean adding a css class; jsPlumb does not, as a rule, impose itself upon a user’s UI any more than this). On collapse, re-route connections to Group elements so that they connect to the Group container. They must remember their original source/target, and when queried they must report their original source/target; the connection to the Group element is just cosmetic.

- add a groupExpand method, which expands a Group, re-routing connections to/from Group elements.

**Comment by sporritt** [comment]
@Deklin @ivosantiago  @herringtown quite a lot of time has passed since any of you expressed an interest in groups, but just wanted to let you know it got released today in jsPlumb 2.1.0.

there's a demo here:

https://jsplumbtoolkit.com/community/demo/groups/index.html

and some docs here:

https://jsplumbtoolkit.com/community/doc/groups.html

**Comment by sporritt** [comment]
i'm going to close this issue; any follow ups/bugs regarding the groups feature can be opened as new issues.
