### ISSUE TITLE
Scroll issue

### ISSUE THREAD

**Issue by bondarenkokv** [sporritt/jsPlumb#329]
Hi guys! 
Thank you for jsPlumb, it's really great thing!
Sorry if it's duplicate issue (I saw scrolling issues below).
But I have next thing: https://jsfiddle.net/FamBBM/rzez5g9q/14/
Connections from numbers are draggable and yellow  rectangle is dropping area. If you don't scroll list everything is ok, but if you'll scroll it and try to drag connection you'll that connection line is string from wrong place.
Could you please give me an advice how to fix?
Thank you!

**Comment by sporritt** [comment]
this fiddle doesn't run....

**Comment by sporritt** [comment]
(it's because the fiddle is loaded via https but then loads up jquery on http; the browser complains)

this fiddle runs

http://jsfiddle.net/FamBBM/rzez5g9q/14/

**Comment by sporritt** [comment]
@bondarenkokv let's use this one; it points to a recent 1.7.3 dev version of jsplumb

http://jsfiddle.net/rzez5g9q/19/

so this issue is kind of related to other issues that have been reported about elements whose parent is scrolled.  it is true that jsPlumb is not taking this into account.

i would like to do something to fix this, and the obvious thing is to just check the `scroll` value of all of the ancestors of some element, but that's unappealing from a performance point of view. Plus, this use case always makes me ask the same question, which noone has yet answered definitively: how exactly do you want this to behave when endpoints are scrolled out of view?

for example, connect the long 9999999.. value to the target and what do you get:

![image](https://cloud.githubusercontent.com/assets/262720/6430283/2831a7f6-c057-11e4-8b69-7813a672c216.png)

this is correct in that the anchor on the number is `RightMiddle`, and that's where the number ends. But the end of the number is hidden. So it looks weird with the connection floating in space like that. should it be hidden? should it be temporarily attached to the list's parent container? 

it's thess questions that make me feel like there is something more to this problem than a tweak to the code that calculates positions. It feels like it's a requirement of the API to support this somehow.  But noone has ever taken me up on the offer.

**Comment by sporritt** [comment]
related to #237

**Comment by bondarenkokv** [comment]
@sporritt Thank you very much for your answers!
I don't have connection floated in space because I have custom connector like this (blue one):
![image](https://cloud.githubusercontent.com/assets/5427785/6437624/48849f06-c0d2-11e4-9523-04755a9296f8.png)


For me issue is only on dragging (even if you'll scroll and start dragging connection from 3 it would have wrong offset) because on dragging I can have only straight connector.
Regarding how it should behave I think current behaviour is correct, if some one have issues with scroll he will attach connection to parent element or redefine connectors.

**Comment by sporritt** [comment]
closing this and moving discussion to #237

**Comment by sporritt** [comment]
actually..reopening. this is newer.

**Comment by sporritt** [comment]
fixed in 1.7.4 dev:

http://jsfiddle.net/rzez5g9q/25/

note you just need `repaintEverything`; you dont need to update the drag offsets.
