### ISSUE TITLE
Bower integration

### ISSUE THREAD

**Issue by NeveHanter** [sporritt/jsPlumb#331]
I suggest stopping appending version numbers to js filenames for bower packages. i.e:
use jquery.jsPlumb.js instead of error prone jquery.jsPlumb-1.7.3.js

**Comment by sporritt** [comment]
thanks for the suggestion but i'm not going to do that. there are discussions on various issues about why not.

**Comment by enapupe** [comment]
Sorry to bring back this subject, but this is causing some issues on my working env.
I have 18 bower dependencies and the only one that change its filename, appending the version number, is jsPlumb.
The problem is that the prod servers cannot benefit security/bug patches automagically, without manual tuning of the file path every time it updates.

Is there any particular reason for naming the files this way?  Can't you simply add a file named jsplumb.min.js mirroring the versioned file? I did a quick look at issue but couldn't find any.
Thanks for your attention.

**Comment by carloschneider** [comment]
+1

**Comment by DHoffm** [comment]
Hi Sporritt can link here to those discussions or issues.

**Comment by sporritt** [comment]
https://github.com/jsplumb/bower-jsplumb
