### ISSUE TITLE
Please move non-GPL compatible demo code to another repository

### ISSUE THREAD

**Issue by stefanruijsenaars** [sporritt/jsPlumb#342]
Relaying from https://www.drupal.org/node/2454629:

> https://github.com/sporritt/jsPlumb/tree/master/demo contains code licensed as Apache2 and a font that appears to also be licensed as Apache 2 (http://www.google.com/fonts/specimen/Open+Sans).
> 
> Including demos in the actual library is general not ideal. I would ask the project maintainers to move the demos to a different repo and add them back during packaging.

**Comment by stefanruijsenaars** [comment]
FYI, the Open Sans font seems to also be included in https://github.com/sporritt/jsPlumb/tree/master/css

**Comment by fernetbianca** [comment]
I am sorry if i've made something wrong. I am a newbie and don't know the
good practice of GT. I have a lot of interest on jsPlumb because his dev is
link to a french project (parsimony). So, if i've done something stupid, i
am sorry and tell me what i have to do It will be done...

Best Regards

2015-03-18 16:33 GMT+01:00 Stefan Ruijsenaars <notifications@github.com>:

> FYI, the Open Sans font seems to also be included in
> https://github.com/sporritt/jsPlumb/tree/master/css
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sporritt/jsPlumb/issues/342#issuecomment-83022595>.
>



-- 
Garrigos adrian
06.64.24.02.02

**Comment by stefanruijsenaars** [comment]
No nothing wrong, this question is for the maintainer (@sporritt)

**Comment by fernetbianca** [comment]
Ok,

By the way... Are you a JS Jedi? I am looking for one, because our project
(parsimony OpenS) is depending on JsPlumb (performance). Il you know one
please help the *project <https://github.com/parsimony/parsimony> *

Help me, Obi Wan Kenobi. You're my only hope.
https://github.com/parsimony/parsimony

2015-03-18 16:43 GMT+01:00 Stefan Ruijsenaars <notifications@github.com>:

> No nothing wrong, this question is for the maintainer (@sporritt
> <https://github.com/sporritt>)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sporritt/jsPlumb/issues/342#issuecomment-83026653>.
>



-- 
Garrigos adrian
06.64.24.02.02

**Comment by sporritt** [comment]
@stefanruijsenaars looks like you got what you needed over on the  drupal issue.  I don't think there's anything to do here.

**Comment by sporritt** [comment]
@fernetbianca do you want to drop me a line and talk about jsPlumb? You're having some performance issues?

**Comment by sporritt** [comment]
@stefanruijsenaars incidentally, do you know what specific code is being referred to in the comment "contains code licensed as Apache2 " ?

**Comment by stefanruijsenaars** [comment]
I guess it's just the fonts (the only mention of "apache" is in https://github.com/sporritt/jsPlumb/blob/master/demo/Apache%20License%20Version%202.txt -- which is accidently located in /demo but seems to refer to the fonts)

Maybe you could use google webfonts instead of distributing the fonts in the repository?

**Comment by sporritt** [comment]
i dont really need the font at all, it's just so the pages look a little nicer.  it will be irrelevant soon anyway when i release the commercial version since the open source version will be hosted on that site.  i may as well remove the font from this repo.

**Comment by sporritt** [comment]
closing. open sans was removed. the site looks better without it anyway; helvetica ftw.
