### ISSUE TITLE
IE and Firefox performance vs chrome

### ISSUE THREAD

**Issue by Deklin** [sporritt/jsPlumb#355]
In our testing, we've noticed (even via the jsplumbtoolkit.com website) that chrome is incredible fast and smooth when moving nodes around. IE and Firefox however, seem to stutter. It is more apparent when the node has a connector coming out of it (using SVG)

The system I am testing on is a dual quad-core with 28gb memory. IE11 and Firefox 37.0.1

I was wondering if this is a known issue?

**Comment by sporritt** [comment]
chrome is generally faster than either FF or IE, yes, but that's true of all sites, not just jsplumb.

if you're talking about this specific demo 

http://jsplumb.org/demo/flowchart/dom.html

there might appear to be 'stuttering' because nodes are snapped to a grid while dragging. outside of that, no, i haven't had anyone report anything like this.

**Comment by Deklin** [comment]
Ok no worries. Firefox seems to do ok now, IE is the worst (but not that bad) IE12 I think is a complete rewrite so anxious to see what they do there.
