### ISSUE TITLE
API Page is broken

### ISSUE THREAD

**Issue by mcometa** [sporritt/jsPlumb#362]
For some reason I am having issues with the API page. If this is related to some future improvement or fix, then just delete the post. Thanks!

Screenshot (apologies for the size of the image, I don't know how to reduce it):
![screen shot 2015-04-21 at 4 10 49 am](https://cloud.githubusercontent.com/assets/66358/7239434/76f10628-e7dc-11e4-8573-e7a386a2f2db.png)

**Comment by sporritt** [comment]
The problem here is that yui is loading its dependencies at runtime and its not using https. I actually thought I had fixed this. In the meantime you can maybe try looking at a beta version of the site that hosts both the open source and commercial versions:

https://beta.jsplumbtoolkit.com/community/apidocs/index.html

**Comment by mcometa** [comment]
The demos on this site are awesome! I am kind of making a "mind mapping"
site and I need your plugin to connect elements. Thanks!


Best Regards,
Marc Cometa
http://mcometa.com

**Comment by sporritt** [comment]
yes something like this one would make a good basis for a mind mapping app:

https://beta.jsplumbtoolkit.com/demos/toolkit/hello-world/index.html

that's one of the commercial demos though.  not sure if you'd noticed that.

**Comment by sporritt** [comment]
that beta site will be live shortly; i won't make any updates to the current site for this. you can use the apidocs but it's just not very pretty.
