### ISSUE TITLE
Weird rendering and drag-drop behaviour with 1.7.4+

### ISSUE THREAD

**Issue by evdtempel** [sporritt/jsPlumb#367]
I'm having weird issues with rendering and drag-and-drop with the releases after 1.7.4 when the window overflows. No issues when using 1.6.5 and 1.7.0 to 1.7.3.

Dragging an element which is positioned outside of the screen (overflow area) makes it snap back to the "visible area" and the arrow will be out of position. 

+When I render the page without any overflow:
![screenshot 2015-04-28 14 14 14](https://cloud.githubusercontent.com/assets/1208705/7369275/ee7eb2b0-edb0-11e4-8c80-f12dccf81367.png)

If I resize the window (cause overflow) scroll down and refresh the page it results in this:
![screenshot 2015-04-28 14 14 30](https://cloud.githubusercontent.com/assets/1208705/7369277/f028edb0-edb0-11e4-98bd-5e497362bf55.png)

I put my code in a JSFiddle to demonstrate both issues 
JSFiddle: http://jsfiddle.net/3kpvy1h5/2/

- Drag-drop: Scroll down and try to move "Problem solved"
- Rendering: The rendering issue will be visible upon scrolling down and using right click to "reload frame"

**Comment by sporritt** [comment]
targeting 1.7.6

**Comment by sporritt** [comment]
The change after 1.7.3 was some code that attempted to handle the scroll in parent elements, because there are situations in which it comes into play. I've found, though, that it's causing more trouble than it solved - you're not the first person to mention this.  Here's a discussion on the groups which I'm sure is related:

https://groups.google.com/forum/#!topic/jsplumb/GwbR7ygMLXE

We could never quite pin down the exact set of circumstances the code should be targeting.

I haven't got it to hand right now but there was one specific use case this code worked for, and it was unusual.  It was related to the eternal question of what to do about joining list items (given they scroll and can disappear from view etc).  

If I can find that other issue I might move this scroll check to a flag and advise the guy who needed it that 1.7.6 has gone back to a more straightforward approach.

**Comment by evdtempel** [comment]
After reading the google group you've linked to, I have been able to solve my problem by giving the containing div a relative/absolute positioning (was default i.e. static). Seems to be intentional(ish), reading your comment https://groups.google.com/d/msg/jsplumb/GwbR7ygMLXE/h22UehRHugUJ.

I've updated the JSFiddle with the relative container, which works as expected: http://jsfiddle.net/3kpvy1h5/3/

I've taken a look at the 1.7.4 milestone issues, and I think this is the one you are referring to: https://github.com/sporritt/jsPlumb/issues/329

**Comment by evdtempel** [comment]
Swapping out line [486](https://github.com/sporritt/jsPlumb/blob/9d8eef2ccfe2bdd31d619bfff7846596adf56c13/src/dom-adapter.js#L486) with the suggestion you [commented](https://groups.google.com/forum/#!msg/jsplumb/GwbR7ygMLXE/h22UehRHugUJ) works with static positioning.

``` JavaScript
if (offsetParent != null && offsetParent !== document.body && (offsetParent.scrollTop > 0 || offsetParent.scrollLeft > 0)) {
```

**Comment by sporritt** [comment]
Thanks for the updates. That line of code did seem to me to be a good solution, but after that point there are a few more scenarios thrown about in which it might not work, so I haven't yet made any changes. 

If you have a moment could you try something else? Could you try commenting out the line of code that calls `maybeAdjustScroll` and see what that does?

**Comment by evdtempel** [comment]
Commenting out [498](https://github.com/sporritt/jsPlumb/blob/9d8eef2ccfe2bdd31d619bfff7846596adf56c13/src/dom-adapter.js#L498) also fixes the issue, retaining static positioning.

**Comment by sporritt** [comment]
ok thanks.  i'll have a think about what might be best to do about this.

**Comment by evdtempel** [comment]
- Commenting out 498 brings back issue #329, [JSFiddle](http://jsfiddle.net/rzez5g9q/26/)
- Swapping out 486 keeps #329 working, [JSFiddle](http://jsfiddle.net/rzez5g9q/27/)

**Comment by evdtempel** [comment]
Created a pull request for line 486 which fixes/keeps both issues working. Haven't tested any other situations. Your call from here ;)

**Comment by sporritt** [comment]
I've pushed the line 486 fix to the 1.7.6 dev branch.  I tested it against another fiddle posted in the group chat I linked to, and that one works too. So this approach looks to be best for everyone.

thanks for taking the time to investigate.

**Comment by sporritt** [comment]
oh sorry i just saw your note about the PR after writing that comment. thanks!

**Comment by sporritt** [comment]
I'm marking this done as I have tested your fiddle against a build of 1.7.6, but note that you still have this issue:

![image](https://cloud.githubusercontent.com/assets/262720/7406537/91d3c206-ef47-11e4-99c2-b7f1811a4fb4.png)


which is caused by the 45 degree transform you're using.  Neither jsPlumb nor jQuery will give you the right answer for these elements' offsets. One option you have is to use SVG for these; another is to use a background image is in this jsPlumb demo:

https://beta.jsplumbtoolkit.com/community/demo/perimeterAnchors/index.html
