### ISSUE TITLE
Single Item Node with Single item not with multiple

### ISSUE THREAD

**Issue by zanetinemanish** [sporritt/jsPlumb#372]
Hi Simon, I tried jsPlumb it was Great plugin but i am stuck here, can you please help me out?
Main thing is here what i want to do! we have 4 Questions and 4 Answers with randomly positioned and user have to point correct question to correct answer, 

Issue: When we Click/Drag on question then user only Click/Drag on single answer not on multiple answers check the video i attached hope you understand well.

Video : http://ph5s.com/video5.mp4

**Comment by sporritt** [comment]
I cant really tell what it is you want to do. Maybe you could create a jsfiddle?

**Comment by sahibsingh** [comment]
Hello @sporritt  here is jsfiddle : http://jsfiddle.net/indianwebdesigner/66869uhy/, you have to click on question and then click on answer.

what we want: when user checked on single item from questions then user have to select one answer, user may not select the answer again.

~Sahib

**Comment by sporritt** [comment]
you can probably just check for an existing target connection before establishing the connection, something like

```
if (jsPlumb.select({target:$(this)[0]}).length == 0) {
  // do you code here
}
```

i noticed you're using 1.3.16. i support only the very latest version (which is now 1.7.5) because i don't have time to support all versions. Also this is not really a jsPlumb question; you could have solved this just by tracking what targets you had already connected. In the future maybe you could try to avoid opening an issue for a question like this. i don't usually answer these sorts of questions here. This tracker is for bugs and enhancements.
