### ISSUE TITLE
Scroll: Batch or doWhileSuspended not working 

### ISSUE THREAD

**Issue by tanbchr** [sporritt/jsPlumb#373]
We were using version 1.5.4 of jsplumb. When we scroll, the connector was following the good target.
On scroll, we call doWhileSuspended to do some calculation and then redraw. In that version everything was working fine.

Here's the fiddle for the version 1.5.4: http://jsfiddle.net/7e9Ea/10/

We updated to version 1.7.5. When we scroll the connections don't follow the target. The update is not done.

Here's the fiddle for version 1.7.5: http://jsfiddle.net/b5xscrek/

We tried with doWhileSuspended and with batch. Both are not working in version 1.7.5. We also tried to call the function repaintEverything, without success.

The function that recalculates is called: recalculateEndpoints().

Any help will be appreciated.

**Comment by tanbchr** [comment]
Can I have some feedback on this issue please.

**Comment by sporritt** [comment]
it could be that you need to use the `revalidate` function rather than `repaint`.

**Comment by sporritt** [comment]
closing this.  the 1.5.4 fiddle doesn't run for me so I can't compare it with what the 1.7.5 one does (which I updated to 1.7.6 because 1.7.5 is not hosted on the jsplumb server now). If this is still an issue maybe it would be possible to create a fiddle that doesn't have all the extra code kicking around? it would make it easier for me to see what is going on.
