### ISSUE TITLE
return false doesn't stop draggable behavior

### ISSUE THREAD

**Issue by BlackDots** [sporritt/jsPlumb#387]
in the start or drag methods, returning false doesn't stop the element from dragging.

**Comment by sporritt** [comment]
Can you provide a jsfiddle?

**Comment by BlackDots** [comment]
Sorry. I shouldn't have reported this as a bug. I was under the mistaken impression that returning false during drag in jquery ui would normally stop the drag. But there has to be some way to stop it? I modified someone's example into this jsfiddle: https://jsfiddle.net/m44hcjuu/10/  (in this case it would stop the drag if it sees the resize event has been triggered. A trivial example since you could just disable the draggable entirely after a resize occurs but I wanted to demonstrate what I meant)

**Comment by BlackDots** [comment]
I posted the issue because in my project, I added jquery ui resizable to the jsplumb elements, and when I resize them, it also triggers the draggable from jsplumb, so the elements move while they are resizing (if you're resizing from the bottom right corner to make it smaller it also moves the element up towards the top left of the screen). I wanted to check if a resize was currently in progress, and if so, prevent draggable behavior. I unfortunately don't have a jsfiddle to show this.

**Comment by sporritt** [comment]
@BlackDots going through my issue list...what's the status of this one, from your point of view?

**Comment by BlackDots** [comment]
I've been able to replicate the draggable/resizable bug in a couple different tests. Here's an example of someone's code that was working fine in the older version:
http://www.freedevelopertutorials.com/jsplumb-tutorial/examples/jsplumb-fully-draggable-resizable-elements-example/
but if you change the script src to https://jsplumbtoolkit.com/js/dom.jsPlumb-1.7.5-min.js (which I believe to be the new version) and hit the "update" button you'll introduce this bug.

Here's a jsfiddle I created by chopping down some of my code, to show the issue without much complication:
https://jsfiddle.net/8n87aan7/9/

To be clear, the issue in question is that the element moves when it's being resized. If you need any more information from me I'd be happy to help. Thanks for your attention to this issue. jsPlumb is a great tool.

**Comment by sporritt** [comment]
@BlackDots Looks like you need to make use of the `filter` parameter on the `draggable` call, like in this fiddle:

https://jsfiddle.net/8n87aan7/10/

```
instance.draggable(jsPlumb.getSelector(".testOfFunctions"), { 
  filter:".ui-resizable-handle"           
});
```

Docs for the draggable library are here:

https://github.com/jsplumb/katavorio/wiki#filtering

I'm going to close this as I'm trying to clean up my issue list for a release. But feel free to reopen if you don't think the issue has been addressed.

**Comment by chipsenkbeil** [comment]
@sporritt, so, I was trying this with the flowchart demo and I'm too much of a beginner to understand what is wrong. Adding the filter to the draggable call for _window_ class elements fixes dragging and resizing happening together, but dragging no longer moves the anchors with it (and the text seems to stay at the same height instead of staying centered).

What else needs to be considered when adding resizing to endpoints?

Oh, and here is a jdFiddle depicting the problem:  https://jsfiddle.net/sfzdb7k3/1

FYI, you guys don't have a newer version of jsPlumb on a CDN, so had to add it to my personal static content server as https://static.senkbeil.org/jsPlumb-2.0.7-min.js

Not sure if there is an alternative you would recommend.

**Comment by sporritt** [comment]
the only problem you had was just that you were mixing `jsPlumb` and `instance`. The `draggable` call, for instance, was on `jsPlumb`, which is an instance of the jsPlumb class, but distinct from the `instance` you also created.

replacing almost every `jsPlumb` call with `instance` gets it to work:

https://jsfiddle.net/sfzdb7k3/2/

the static `jsPlumb` is something we're thinking of retiring in version 2.1.0.  it's simple enough to get a new instance, and we see confusing situations like this from time to time.

**Comment by sporritt** [comment]
btw - the text issue, that's just because that demo uses a lazy trick to put the text in the middle: it sets `line-height` to the same value as `height`.  There are better solutions; their applicability varies amongst browsers.  You can see a discussion of several here:

http://stackoverflow.com/questions/8865458/how-to-align-text-vertically-center-in-div-with-css

Flexbox is cool but not very well supported yet in IE.  There's a link on that page to another technique:

https://css-tricks.com/centering-in-the-unknown/

which looks like it gets the job done too. as per usual with web dev, there are a million ways to do this. you just have to choose the one that makes you feel the least sullied.

**Comment by chipsenkbeil** [comment]
@sporritt you are totally amazing! Thank you so much for the explanations! Above and beyond what I had hoped for. :)

**Comment by sporritt** [comment]
@chipsenkbeil glad you found them useful!

**Comment by websitewill** [comment]
I recently stumbled upon this issue with the latest versions of jsPlumb and jquery-ui. Anyone know the fix?
I tried handling the drag stuff with JQuery-ui instead of jsPlumb, but when I do that, all my connections don't move with the thing being dragged.

I agree that this is a relatively "new" bug in jsPlumb. Also, sorry to drag up an old post, but it's the most relevant place I have found to ask about this.

Thanks,
Will

**Comment by adriantdf** [comment]
> I recently stumbled upon this issue with the latest versions of jsPlumb and jquery-ui. Anyone know the fix?
> I tried handling the drag stuff with JQuery-ui instead of jsPlumb, but when I do that, all my connections don't move with the thing being dragged.
> 
> I agree that this is a relatively "new" bug in jsPlumb. Also, sorry to drag up an old post, but it's the most relevant place I have found to ask about this.
> 
> Here is a jsfiddle for it: https://jsfiddle.net/sfzdb7k3/116/
> 
> Thanks,
> Will

add this filter to the drag options. It was wrote by sporritt up in the post:
instance.draggable($(".window"), {
   filter: ".ui-resizable-handle"
   });
