### ISSUE TITLE
jsPlumb Vanilla Anchor Bug?

### ISSUE THREAD

**Issue by Bl4ckM** [sporritt/jsPlumb#413]
Hi,

i've just done a jsfiddle example. With any padding applied through e.g. bootstrap's navbar this error occurs:

https://jsfiddle.net/f5bxgzLu/

Any ideas how to fix this issue?

**Comment by sporritt** [comment]
you need to set `position:relative` on the `#canvas` element.

![image](https://cloud.githubusercontent.com/assets/262720/9084049/e86b03f6-3bb2-11e5-8005-ae1ea9c03fe6.png)

**Comment by Bl4ckM** [comment]
wow... i tried to add position:relative to canvas and other elements, why all elements needs to be relative?

**Comment by sporritt** [comment]
it's not all elements that need to be `relative`: just the container.  the nodes should be `absolute`, because you want to drag them.  An `absolute` positioned node will position itself wrt the first explicit `relative` parent, or the body if none found. In your case the first `relative` parent was not the container.

**Comment by alanhg** [comment]
@sporritt 
![image](https://user-images.githubusercontent.com/9245110/34200470-2aa1afa4-e5ac-11e7-9535-c8615f2471f8.png)
anchor position is wrong, How to solve it?

![image](https://user-images.githubusercontent.com/9245110/34200525-5f565b5a-e5ac-11e7-8c27-507dffa3bc67.png)

I use jsplumb in bootstrap.
