### ISSUE TITLE
Performance problem with addEndpoint

### ISSUE THREAD

**Issue by rslabon** [sporritt/jsPlumb#442]
I have problem with adding endpoints, lots of them (~3000). For performance improvement I have set suspendDrawing to true but when I have profiled my app using chrome profiler I see that addEndpoint method invokes:
addEndpoint -> _newEndpoint -> _manage -> _updateOffset -> getSize

When suspendDrawning is set to true any calculations of positions/dimensions have big impact on performance...

Are those calculations needed when suspendDrawing is set to true?

**Comment by sporritt** [comment]
that's a good question. i don't know. Are you adding multiple endpoints to the same element? If you've got 3000 unique elements then you're gonna have to deal with a lag somewhere, since jsPlumb needs to know the size of all those elements. If you're putting a bunch of endpoints onto each element, though, then it seems likely that not running those calculations while drawing is suspended could save some time.  But as for whether that would affect the operation of jsPlumb, I'd have to just test it and see.

**Comment by rslabon** [comment]
I agree that having too much elements on a page slows down page responsiveness. The problem is with even small number of endpoints, if adding endpoint takes ~1ms(computing getSize) and I have to show 100 endpoints that means for just adding endpoints I have ~100ms and if I set suspend drawing the ~100ms is just wasted on getSize which is not use when suspend drawing is on.

**Comment by sporritt** [comment]
but are you adding multiple endpoints to each element?

**Comment by rslabon** [comment]
No, I'm adding one endpoint per element

**Comment by sporritt** [comment]
ok. so that makes it less straightforward to optimise this out, probably, since jsPlumb is going to need to find out the dimension of each element at some stage. It can either do it when it first becomes aware of an element and then not when it repaints, or do it when it repaints. but either way, it has to do it at least once.

**Comment by rslabon** [comment]
I think the problem is with reflows and repaints. Adding endpoint triggers adding attributes to DOM element and computing offsets/dimensions. Changing the DOM and then reading properties like offsets triggers repaints and reflows. This makes reading properties very expensive... 

I think it would be better to read offsets after adding all endpoints. This solution avoids reflows and repaints. 

Nice article about reflows: http://www.stubbornella.org/content/2009/03/27/reflows-repaints-css-performance-making-your-javascript-slow/

**Comment by sporritt** [comment]
Yes its reflows. I mean that they have to happen sometime if jsplumb is going to know about the dimensions of your elements.

**Comment by Helen1987** [comment]
So, is there any way to improve performance, when I have to add 3000 endpoints?
