### ISSUE TITLE
Suggestion: event proxy for connectors

### ISSUE THREAD

**Issue by dbnoble** [sporritt/jsPlumb#474]
Sometimes the connectors can be relatively small, especially if you're zooming out, and that can make it a bit hard to actually hover or click on the connector itself. Also, when using a dash array, the default pointer-events property is set to visible-stroke, which means the transparent sections don't always capture the events.

I am proposing the possibility to have a second "ghost" path that allows us to add some 'padding' area to pick up pointer events. The use case I have in mind would be for the proxy path to be transparent, but if we could pass paint style parameters to it also, it could make for some cool looking connectors.

I've built an example you can play with here: http://codepen.io/vertical3/pen/gPvVXr

Obviously my implementation here is quick and dirty, just needed to be able to show what I was going for.

**Comment by sporritt** [comment]
do you know about the `outline`  and `outlineStyle` parameters?  They're used on most of the jsPlumb demos, like this one:

https://jsplumbtoolkit.com/community/demo/flowchart/index.html

![image](https://cloud.githubusercontent.com/assets/262720/12549209/c50fdd84-c3af-11e5-8f1a-d56fcceaf0e5.png)

to do what you're talking about. in this case of course I used `white`. But I use `transparent` most of the time.

**Comment by dbnoble** [comment]
Well, I feel silly! I admit I've seen that before but it didn't occur to me to use that.

Unless I'm doing something wrong, it looks totally whack when you use that with a dashed line. It doesn't appear to even match up with the existing dash array, any ideas there? I would prefer a solid SVG that follows the entire path.

**Comment by dbnoble** [comment]
BTW, while we're here, it took me like 2 hours to realize why I couldn't get the jsplumb-hover class to show up on the connector. Apparently if you don't supply a connectorHoverStyle in the params, the class won't get added on hover, which means I have to arbitrarily pass styles there just so I can grab that class programatically later.

Great job with this library by the way, I really love it.

**Comment by sporritt** [comment]
`jsplumb-hover` should always be added to a Connector when it is being hovered. are you certain you're not seeing it?

This issue touches on something that I've been hesitant to make a final decision on: none of the `***Style` parameters are really necessary given that SVG can be used to style everything. The first version of jsPlumb used a Canvas element so these were necessary, and VML (for IE8 and below) also does not support CSS for styling, so they've lingered around. Since the 2.0 versions support only SVG you could argue that we could mandate using CSS for styles and toss out the style parameters. I can't commit to doing that, though, since I have this vague notion of jsPlumb being used on the server at some point (not with Phantom; with no knowledge of browsers at all).

The outline connector is assigned a class of `jsplumb-connector-outline`.  You could write styles targeting that class to override the dash stuff. But I think you'd have to make them `!important` since they need to override attributes on the element.

**Comment by dbnoble** [comment]
Thanks, setting CSS properties on the `jsplumb-connector-outline` class works. It would be nice if the SVG element itself had some reference back to the connection or scope it belongs to so I could access them without having to get the `connection` object first.

About the hover class, my confusion was based on some weird behavior - when viewing the element in Chrome's developer tools, the class attribute never changes when I hover UNLESS I also specify `connectorHoverStyle`. So I built a function to grab the class attribute on the svg element and display the list of classes on the page so I could show you, and oddly enough it does show the `jsplumb-hover` in the class list and it is actually getting applied even though it never changes in the element view when connectorHoverStyle is absent. This is probably due to the way the browser shims for SVG element manipulation.
