### ISSUE TITLE
anchor positions

### ISSUE THREAD

**Issue by elgubenis** [sporritt/jsPlumb#518]
hi, I recorded an example of anchors not working as expected:

http://www.giphy.com/gifs/3o6ozn97oh6CJmyPFm

i thought the anchors are going on each face/side of the div element, but it seems like they go everywhere in the element and the dragging decides the direction. Also in the end, even if I started dragging from a top face, the final connection and endpoints are on the bottom of both elements.

code:
```js
    plumb.makeSource('red', { allowLoopback: false });
    plumb.makeTarget('red', { allowLoopback: false });
    plumb.makeTarget('blue', { allowLoopback: false });
    plumb.makeSource('blue', { allowLoopback: false });
```

these are my defaults
```js
const defaults = {};

defaults.Overlays = [
  ['Arrow', {
    location: 1,
    id: 'arrow',
    length: 5,
    width: 10,
    foldback: 0.7,
  }],
];

defaults.Connector = [
  ['Flowchart'],
];

defaults.Anchors = ['Top', 'Bottom', 'Left', 'Right'];

defaults.Endpoint = ['Dot', {
  radius: 3,
  cssClass: 'endpoint-hidden',
  hoverClass: 'endpoint-active',
}];

defaults.MaxConnections = -1;

defaults.PaintStyle = { lineWidth: 1, strokeStyle: '#000' };

module.exports = defaults;
```

also, the 2 elements are non-draggable, when i add the draggable, it looks like this:
http://www.giphy.com/gifs/l3V0JdFQTtBENtU52

code:
```js
    plumb.makeSource('red', { allowLoopback: false });
    plumb.makeTarget('red', { allowLoopback: false });
    plumb.makeTarget('blue', { allowLoopback: false });
    plumb.makeSource('blue', { allowLoopback: false });

    plumb.draggable('red');
    plumb.draggable('blue');
```

**Comment by elgubenis** [comment]
this gif shows a buggy connection, but you can see that on both elements all the anchors seem to be in the top-left corner: http://www.giphy.com/gifs/3o6oztUtgrnlmmVjWg maybe that helps for knowing whats wrong?

**Comment by elgubenis** [comment]
also, a maybe hint: the grid: [50, 50] properties of the draggable don't do a thing, not sure if that has something to do with my issue, but it just won't take a grid into account.

**Comment by elgubenis** [comment]
I've commented the makeSource,makeTarget methods and add an endpoint by hand and it seems to work:

```js
    // plumb.makeSource(this.ui.connectables, { allowLoopback: false });
    // plumb.makeTarget(this.ui.connectables, { allowLoopback: false });

    plumb.addEndpoint(this.ui.connectables, {
      isTarget: true,
      isSource: true,
      endpoint: 'Dot',
      paintStyle: {
        strokeStyle: '#000',
        fillStyle: 'transparent',
        radius: 5,
        lineWidth: 1,
      },
      connector: ['Flowchart', {
        stub: [40, 60],
        gap: 10,
        cornerRadius: 5,
        alwaysRespectStubs: true,
      }],
      dragOptions: {},
      overlays: [
          ['Label', {
            location: [0.5, 1.5],
            label: 'Drag',
            cssClass: 'endpointSourceLabel',
            visible: false,
          }],
      ],
    });
```

but i only get an endpoint (anchor?) on the bottom of each element

**Comment by sporritt** [comment]
i don't think you've found a bug, or if you have i don't think it is what you think it is.  the default anchor location is `Bottom`, which is what it showing in your first image. Every connection uses that anchor position so they all pile up on top of each other.

`defaults.Anchors = ['Top', 'Bottom', 'Left', 'Right'];`

in theory would actually tell jsPlumb to use `Top` as the source anchor and `Bottom` as the target. This is what i think is possibly a bug, but I think that you expect that syntax to choose from the four positions, possibly in rotation, I'm not sure. If you change it to `defaults.Anchor=...` (drop the S) then you will have instructed jsPlumb to use a [dynamic anchor](https://jsplumbtoolkit.com/community/doc/anchors.html#dynamic), which should choose from the four locations. But note that it does not choose from the available locations in rotation. If you have two connections for which a combination of Left-Right is appropriate, say, then those connections will be drawn on top of each other.

if you want a separate location for each connection you need to use [continuous anchors](https://jsplumbtoolkit.com/community/doc/anchors.html#continuous).


regarding the 'buggy connection' shown in one of your gifs, if you mean the fact that the connection wont drag, that is due to you having configured the element both as a draggable and as a draggable connection source. you need to use a `filter` to identify some part of your element that will act as the connection drag source.

https://jsplumbtoolkit.com/community/doc/connections.html#sourcefilter

**Comment by elgubenis** [comment]
thank you very much for your detailed explanation, I guess I just got everything wrong, it was a little difficult to understand (but good) to have the anchor and endpoints separated. now I just make an endpoint for every Anchor (sounds clear now.. writing that after getting it done) and everything works as expected.

**Comment by sporritt** [comment]
great! glad you got it working.
